# Generated by Django 3.2.12 on 2022-05-25 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('questions_number', models.IntegerField(default=10)),
                ('questions', models.CharField(max_length=800)),
                ('answers', models.CharField(max_length=700)),
            ],
        ),
    ]
