# Generated by Django 3.2.12 on 2022-06-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeTests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='questions_number',
        ),
        migrations.AddField(
            model_name='questions',
            name='resposta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
