# Generated by Django 3.2.12 on 2022-06-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeTests', '0002_auto_20220603_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(max_length=8000),
        ),
    ]
