# Generated by Django 3.2.12 on 2022-06-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeTests', '0003_alter_questions_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='questions',
        ),
    ]
