# Generated by Django 3.2.12 on 2022-05-25 13:48

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.CharField(blank=True, choices=[('01', '5'), ('02', '10'), ('03', '15'), ('04', '20')], max_length=3)),
                ('types', models.CharField(blank=True, choices=[('text', 'text'), ('analise', 'analise'), ('curso', 'curso')], max_length=8)),
                ('title', models.CharField(max_length=25)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('video', models.URLField()),
                ('theme', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=95)),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('is_superuser', models.BooleanField(blank=True, default=False)),
                ('username', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=18)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('premium', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
